branches:
  only:
  - develop
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "chenfjm"
- git config --global user.email "chenfjm@gmail.com"
- git clone --branch gh-pages https://github.com/chenfjm/vue-ghpages-blog.git dist
install:
- npm install
script:
- npm test
- npm run build
after_script:
- cd dist
- echo "chencheng.sn.cn" > CNAME
- cp index.html 404.html
- git add --all .
- git commit --message "Automatically update from travis-ci"
- git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
env:
  global:
  - GH_REF: github.com/chenfjm/vue-ghpages-blog.git
  - secure: kkOhqRH2qkFGlTbkfccyCANxyzBqrbBBd2MtObF4SXsnWjfqFP58VnIwdZUeMrNDyBtyjgXnnU5wfwBP75VNCKXSxI46MkHShPLBERLbLJZfschn74vu1ScNboay5S7JkTeL/biGS3RsJL8HUguBMB8Z20eh0gs/SBI7o2mFczpmozXzea3ArP6Jby5pZIW4OQ+PQf2+2InPu+oZTtf9Hb+DrpNR2fUy6FyVR5rtE8lU2FCEiSnwZfJhU8NNoqZV3i5TmjKZy/hehJVPKMt9Ly+ALPPC9xwEqmFxyWfsWeRQA6kBjLb07EmgmCOg0CbHBB2rrwCnCU4JuOrd+vE5ofl4RSqWTpbbjTPTi3ZBW5amzuxvLgczR3B4m5f46hz7Vi8GsphhYPPA27sgxm8Z/CbR0juBYr4XDw9sl70jbNBNtyDAkuiR+DwRCD8Ra+5qaSiBWgaJJkHd+kgki3/GSevdbtVrw6XM8FjhINxO6raYQgEOETsFuT5y1lIf6RQvX1OVPQ+RXRoCaZ3EvfeVh+3uSm3QOHtFkxKsxjmwkTvj+HUJiElLGR3ejHGK8NmZ8kErvUwz4nsX9gPY2WOFAc+1d3vzYWJF55pNBA3sFpYWWlLUKDfVqHyorJGPx/cPcAXM1mYivjq+Mrc0+G3x1fDwM+nX3wrCz/Av9L8vvqc=
